# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


num1 = 1 
num2 = 2
total = 0
EvenValues = 0
while total < 400000:
    total = num1 + num2
    num1 = num2
    num2 = total
    if total % 2 == 0:
        EvenValues +=total
print(EvenValues)